[package]
name = "lorri"
# See MAINTAINERS.md for details about versioning
version = "1.8.0" # Format: MAJOR.MINOR.0
authors = [
    "Graham Christensen <graham.christensen@target.com>",
    "Profpatsch <mail@profpatsch.de>",
]
homepage = "https://github.com/nix-community/lorri"
license = "Apache-2.0"
edition = "2021"

# before updating dependencies: we want to keep the rustc compatible with 1.41.0 for now (start of 2020).
[dependencies]
# central features
notify = { version = "8.0.0", default-features = false, features = ["macos_fsevent"] }
notify-debouncer-full = { version = "0.5.0", default-features = false }
atomicwrites = "0.4.4"
nix = { version = "0.29.0", features = ["poll", "fs"], default-features = true }
regex = "1.11.1"
tempfile = "3.16.0"
anyhow = "1.0.95"
thiserror = "2.0.11"
tokio = { features = ["rt", "macros", "net", "time", "io-util", "io-std", "sync", "process", "fs"], version = "1.43.0" }
clap = { version = "4.5.30", features = ["derive", "error-context"] }
tokio-rusqlite = { version = "0.6.0", features = ["bundled"] }
rusqlite = { version = "0.32.1", features = ["bundled"] }

# logging;
slog = { version = "2.7.0", features = [
    "release_max_level_debug",
] } # enable debug messages in the release so that --verbose still works
slog-term = "2.9.1"
fastrand = "2.3.0"
# serialization
serde = "1.0.217"
serde_derive = "1.0.217"
serde_json = "1.0.138"
# nice-to-have
ctrlc = { version = "3.4.5", features = ["termination"] }
directories = "6.0.0"
md5 = "0.7.0"
vec1 = "1.12.1"
itertools = "0.12.1"
# crash reporting
urlencoding = "2.1.3"
os_info = { version = "3.10.0", default-features = false }
backtrace = "0.3.74"

