name: CI
on:
  pull_request:
    branches: ["**"]
  push:
    branches: [master]
  workflow_dispatch: {}
jobs:
  go-test-ubuntu:
    name: Go tests (ubuntu-latest)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6.0.2
      - uses: cachix/install-nix-action@v31.10.4
      - uses: cachix/cachix-action@v17
        with:
          name: nix-community
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
      - name: Run tests
        run: nix develop .#ci --command go test ./...

  go-test-macos:
    name: Go tests (macos-latest)
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v6.0.2
      - uses: cachix/install-nix-action@v31.10.4
      - uses: cachix/cachix-action@v17
        with:
          name: nix-community
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
      - name: Run tests
        run: nix develop .#ci --command go test ./...

  nix-build-ubuntu:
    name: nix build (ubuntu-latest)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6.0.2
      - uses: cachix/install-nix-action@v31.10.4
      - uses: cachix/cachix-action@v17
        with:
          name: nix-community
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
      - name: Build
        run: nix build

  nix-build-macos:
    name: nix build (macos-latest)
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v6.0.2
      - uses: cachix/install-nix-action@v31.10.4
      - uses: cachix/cachix-action@v17
        with:
          name: nix-community
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
      - name: Build
        run: nix build
